version: '3.9'

volumes:
    logs:
        driver: local

networks:
    app-tier:
        driver: bridge

services:
    memcached:
        image: memcached:latest
        ports:
            - 11211:11211
        networks:
            - app-tier

    memcacheadmin:
        image: hatamiarash7/memcached-admin:master
        environment:
            - MEMCACHED_HOST=memcached:11211
        ports:
            - 8081:80
        networks:
            - app-tier

    mongodb:
        image: mongo:latest
        environment:
            - MONGO_INITDB_ROOT_USERNAME=docker
            - MONGO_INITDB_ROOT_PASSWORD=mongopw
        volumes:
            - ./runtime/mongo/data/:/data/db/
            - ./runtime/logs:/var/logs
        ports:
            - 27017:27017
        networks:
            - app-tier
        restart: always

    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_USER: 'docker'
            MYSQL_PASSWORD: 'password'
            MYSQL_DATABASE: 'slimdemo'
        volumes:
            - ./runtime/mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - app-tier
        restart: always

    app:
        build: docker
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        volumes:
            - .:/var/www
            - ./runtime/logs:/var/logs
        ports:
            - 8080:8080
        networks:
            - app-tier
        restart: always
